-- MySQL Script generated by MySQL Workbench
-- Thu Jun  9 09:19:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tank` DEFAULT CHARACTER SET utf8 ;
USE `tank` ;

-- -----------------------------------------------------
-- Table `tank`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tank`.`Users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstName` VARCHAR(30) NOT NULL,
  `lastName` VARCHAR(30) NOT NULL,
  `userMail` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `userMail_UNIQUE` (`userMail` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tank`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tank`.`Articles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `productId` INT NOT NULL,
  `chassisNumber` VARCHAR(20) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `imageName` VARCHAR(255) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` LONGTEXT NOT NULL,
  `password` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `productId_UNIQUE` (`productId` ASC) VISIBLE,
  UNIQUE INDEX `chassisNumber_UNIQUE` (`chassisNumber` ASC, `name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tank`.`Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tank`.`Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tank`.`Articles_has_Categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tank`.`Articles_has_Categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Articles_id` INT NOT NULL,
  `Categories_id` INT NOT NULL,
  INDEX `fk_Articles_has_Categories_Categories1_idx` (`Categories_id` ASC) VISIBLE,
  INDEX `fk_Articles_has_Categories_Articles_idx` (`Articles_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Articles_has_Categories_Articles`
    FOREIGN KEY (`Articles_id`)
    REFERENCES `tank`.`Articles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articles_has_Categories_Categories1`
    FOREIGN KEY (`Categories_id`)
    REFERENCES `tank`.`Categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
